language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
    - gui/node_modules
    - server/node_modules
addons:
  apt:
    packages:
      - libasound2-dev
install:
  - npm ci
  - (cd server && npm ci)
  - (cd gui && npm ci)
script:
  - npx check-engine
  - (cd server && npm run build)
  - (cd gui && npm run build)
