language: node_js
node_js:
- '8'
cache:
  directories:
  - gui/node_modules
  - server/node_modules
addons:
  apt:
    packages:
    - libasound2-dev
install:
- (cd server && npm install)
- (cd gui && npm install)
script:
- (cd server && npm run build)
- (cd gui && npm test -- --coverage && npm run build)
