language: node_js
node_js:
- '8'
cache:
  directories:
  - gui/node_modules
  - server/node_modules
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - libasound2-dev
install:
- npm install -g npm@5.7.1
- (cd server && npm ci)
- (cd gui && npm ci)
script:
- (cd server && npm run build)
- (cd gui && npm run build)
- docker build --tag phjardas/tabidisco .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
