language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
    - gui/node_modules
    - server/node_modules
addons:
  apt:
    packages:
      - libasound2-dev
install:
  - npm install -g npm@5.7.1
  - npm install
script:
  - npm run build
