language: node_js
node_js:
- '8'
cache:
  directories:
  - gui/node_modules
  - server/node_modules
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libasound2-dev
install:
- (cd server && npm install)
- (cd gui && npm install)
script:
- (cd server && npm run build)
- (cd gui && npm run build)
