plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'

packageExtensions:
  '@apollographql/apollo-tools@*':
    peerDependencies:
      graphql: '*'
  apollo-link-error@*:
    peerDependencies:
      graphql: '*'
  apollo-link-ws@*:
    peerDependencies:
      graphql: '*'
  apollo-upload-client@*:
    peerDependencies:
      graphql: '*'
  '@apollo/react-hooks@*':
    peerDependencies:
      apollo-utilities: '*'
